/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as adminUsuariosRouteImport } from './routes/(admin)/usuarios'
import { Route as adminSucursalesRouteImport } from './routes/(admin)/sucursales'
import { Route as adminRolesAuditoriaRouteImport } from './routes/(admin)/roles-auditoria'
import { Route as adminRolesRouteImport } from './routes/(admin)/roles'
import { Route as adminRegistrosRouteImport } from './routes/(admin)/registros'
import { Route as adminProductosRouteImport } from './routes/(admin)/productos'
import { Route as adminPasosWizardRouteImport } from './routes/(admin)/pasos-wizard'
import { Route as adminMarcasRouteImport } from './routes/(admin)/marcas'
import { Route as adminEmpresasRouteImport } from './routes/(admin)/empresas'
import { Route as adminDashboardRouteImport } from './routes/(admin)/dashboard'
import { Route as adminCategoriasRouteImport } from './routes/(admin)/categorias'
import { Route as adminLayoutRouteImport } from './routes/(admin)/_layout'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const adminUsuariosRoute = adminUsuariosRouteImport.update({
  id: '/(admin)/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const adminSucursalesRoute = adminSucursalesRouteImport.update({
  id: '/(admin)/sucursales',
  path: '/sucursales',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRolesAuditoriaRoute = adminRolesAuditoriaRouteImport.update({
  id: '/(admin)/roles-auditoria',
  path: '/roles-auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRolesRoute = adminRolesRouteImport.update({
  id: '/(admin)/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRegistrosRoute = adminRegistrosRouteImport.update({
  id: '/(admin)/registros',
  path: '/registros',
  getParentRoute: () => rootRouteImport,
} as any)
const adminProductosRoute = adminProductosRouteImport.update({
  id: '/(admin)/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const adminPasosWizardRoute = adminPasosWizardRouteImport.update({
  id: '/(admin)/pasos-wizard',
  path: '/pasos-wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const adminMarcasRoute = adminMarcasRouteImport.update({
  id: '/(admin)/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const adminEmpresasRoute = adminEmpresasRouteImport.update({
  id: '/(admin)/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const adminDashboardRoute = adminDashboardRouteImport.update({
  id: '/(admin)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const adminCategoriasRoute = adminCategoriasRouteImport.update({
  id: '/(admin)/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/(admin)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categorias': typeof adminCategoriasRoute
  '/dashboard': typeof adminDashboardRoute
  '/empresas': typeof adminEmpresasRoute
  '/marcas': typeof adminMarcasRoute
  '/pasos-wizard': typeof adminPasosWizardRoute
  '/productos': typeof adminProductosRoute
  '/registros': typeof adminRegistrosRoute
  '/roles': typeof adminRolesRoute
  '/roles-auditoria': typeof adminRolesAuditoriaRoute
  '/sucursales': typeof adminSucursalesRoute
  '/usuarios': typeof adminUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categorias': typeof adminCategoriasRoute
  '/dashboard': typeof adminDashboardRoute
  '/empresas': typeof adminEmpresasRoute
  '/marcas': typeof adminMarcasRoute
  '/pasos-wizard': typeof adminPasosWizardRoute
  '/productos': typeof adminProductosRoute
  '/registros': typeof adminRegistrosRoute
  '/roles': typeof adminRolesRoute
  '/roles-auditoria': typeof adminRolesAuditoriaRoute
  '/sucursales': typeof adminSucursalesRoute
  '/usuarios': typeof adminUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/(admin)/_layout': typeof adminLayoutRoute
  '/(admin)/categorias': typeof adminCategoriasRoute
  '/(admin)/dashboard': typeof adminDashboardRoute
  '/(admin)/empresas': typeof adminEmpresasRoute
  '/(admin)/marcas': typeof adminMarcasRoute
  '/(admin)/pasos-wizard': typeof adminPasosWizardRoute
  '/(admin)/productos': typeof adminProductosRoute
  '/(admin)/registros': typeof adminRegistrosRoute
  '/(admin)/roles': typeof adminRolesRoute
  '/(admin)/roles-auditoria': typeof adminRolesAuditoriaRoute
  '/(admin)/sucursales': typeof adminSucursalesRoute
  '/(admin)/usuarios': typeof adminUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categorias'
    | '/dashboard'
    | '/empresas'
    | '/marcas'
    | '/pasos-wizard'
    | '/productos'
    | '/registros'
    | '/roles'
    | '/roles-auditoria'
    | '/sucursales'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/categorias'
    | '/dashboard'
    | '/empresas'
    | '/marcas'
    | '/pasos-wizard'
    | '/productos'
    | '/registros'
    | '/roles'
    | '/roles-auditoria'
    | '/sucursales'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/(admin)/_layout'
    | '/(admin)/categorias'
    | '/(admin)/dashboard'
    | '/(admin)/empresas'
    | '/(admin)/marcas'
    | '/(admin)/pasos-wizard'
    | '/(admin)/productos'
    | '/(admin)/registros'
    | '/(admin)/roles'
    | '/(admin)/roles-auditoria'
    | '/(admin)/sucursales'
    | '/(admin)/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  adminLayoutRoute: typeof adminLayoutRoute
  adminCategoriasRoute: typeof adminCategoriasRoute
  adminDashboardRoute: typeof adminDashboardRoute
  adminEmpresasRoute: typeof adminEmpresasRoute
  adminMarcasRoute: typeof adminMarcasRoute
  adminPasosWizardRoute: typeof adminPasosWizardRoute
  adminProductosRoute: typeof adminProductosRoute
  adminRegistrosRoute: typeof adminRegistrosRoute
  adminRolesRoute: typeof adminRolesRoute
  adminRolesAuditoriaRoute: typeof adminRolesAuditoriaRoute
  adminSucursalesRoute: typeof adminSucursalesRoute
  adminUsuariosRoute: typeof adminUsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/usuarios': {
      id: '/(admin)/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof adminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/sucursales': {
      id: '/(admin)/sucursales'
      path: '/sucursales'
      fullPath: '/sucursales'
      preLoaderRoute: typeof adminSucursalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/roles-auditoria': {
      id: '/(admin)/roles-auditoria'
      path: '/roles-auditoria'
      fullPath: '/roles-auditoria'
      preLoaderRoute: typeof adminRolesAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/roles': {
      id: '/(admin)/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof adminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/registros': {
      id: '/(admin)/registros'
      path: '/registros'
      fullPath: '/registros'
      preLoaderRoute: typeof adminRegistrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/productos': {
      id: '/(admin)/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof adminProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/pasos-wizard': {
      id: '/(admin)/pasos-wizard'
      path: '/pasos-wizard'
      fullPath: '/pasos-wizard'
      preLoaderRoute: typeof adminPasosWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/marcas': {
      id: '/(admin)/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof adminMarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/empresas': {
      id: '/(admin)/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof adminEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/dashboard': {
      id: '/(admin)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof adminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/categorias': {
      id: '/(admin)/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof adminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/_layout': {
      id: '/(admin)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  adminLayoutRoute: adminLayoutRoute,
  adminCategoriasRoute: adminCategoriasRoute,
  adminDashboardRoute: adminDashboardRoute,
  adminEmpresasRoute: adminEmpresasRoute,
  adminMarcasRoute: adminMarcasRoute,
  adminPasosWizardRoute: adminPasosWizardRoute,
  adminProductosRoute: adminProductosRoute,
  adminRegistrosRoute: adminRegistrosRoute,
  adminRolesRoute: adminRolesRoute,
  adminRolesAuditoriaRoute: adminRolesAuditoriaRoute,
  adminSucursalesRoute: adminSucursalesRoute,
  adminUsuariosRoute: adminUsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
