/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as adminUsuariosRouteImport } from './routes/(admin)/usuarios'
import { Route as adminTiposSeccionRouteImport } from './routes/(admin)/tipos-seccion'
import { Route as adminTiposAtributoRouteImport } from './routes/(admin)/tipos-atributo'
import { Route as adminSuscriptoresRouteImport } from './routes/(admin)/suscriptores'
import { Route as adminSucursalesRouteImport } from './routes/(admin)/sucursales'
import { Route as adminServiciosRouteImport } from './routes/(admin)/servicios'
import { Route as adminSeccionesRouteImport } from './routes/(admin)/secciones'
import { Route as adminRolesAuditoriaRouteImport } from './routes/(admin)/roles-auditoria'
import { Route as adminRolesRouteImport } from './routes/(admin)/roles'
import { Route as adminRegistrosRouteImport } from './routes/(admin)/registros'
import { Route as adminProductosRouteImport } from './routes/(admin)/productos'
import { Route as adminPasosWizardRouteImport } from './routes/(admin)/pasos-wizard'
import { Route as adminMenusRouteImport } from './routes/(admin)/menus'
import { Route as adminMarcasRouteImport } from './routes/(admin)/marcas'
import { Route as adminIndustriasRouteImport } from './routes/(admin)/industrias'
import { Route as adminFootersRouteImport } from './routes/(admin)/footers'
import { Route as adminEmpresasRouteImport } from './routes/(admin)/empresas'
import { Route as adminDashboardRouteImport } from './routes/(admin)/dashboard'
import { Route as adminContactosRouteImport } from './routes/(admin)/contactos'
import { Route as adminCategoriasRouteImport } from './routes/(admin)/categorias'
import { Route as adminAtributosRouteImport } from './routes/(admin)/atributos'
import { Route as adminLayoutRouteImport } from './routes/(admin)/_layout'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const adminUsuariosRoute = adminUsuariosRouteImport.update({
  id: '/(admin)/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const adminTiposSeccionRoute = adminTiposSeccionRouteImport.update({
  id: '/(admin)/tipos-seccion',
  path: '/tipos-seccion',
  getParentRoute: () => rootRouteImport,
} as any)
const adminTiposAtributoRoute = adminTiposAtributoRouteImport.update({
  id: '/(admin)/tipos-atributo',
  path: '/tipos-atributo',
  getParentRoute: () => rootRouteImport,
} as any)
const adminSuscriptoresRoute = adminSuscriptoresRouteImport.update({
  id: '/(admin)/suscriptores',
  path: '/suscriptores',
  getParentRoute: () => rootRouteImport,
} as any)
const adminSucursalesRoute = adminSucursalesRouteImport.update({
  id: '/(admin)/sucursales',
  path: '/sucursales',
  getParentRoute: () => rootRouteImport,
} as any)
const adminServiciosRoute = adminServiciosRouteImport.update({
  id: '/(admin)/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const adminSeccionesRoute = adminSeccionesRouteImport.update({
  id: '/(admin)/secciones',
  path: '/secciones',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRolesAuditoriaRoute = adminRolesAuditoriaRouteImport.update({
  id: '/(admin)/roles-auditoria',
  path: '/roles-auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRolesRoute = adminRolesRouteImport.update({
  id: '/(admin)/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRegistrosRoute = adminRegistrosRouteImport.update({
  id: '/(admin)/registros',
  path: '/registros',
  getParentRoute: () => rootRouteImport,
} as any)
const adminProductosRoute = adminProductosRouteImport.update({
  id: '/(admin)/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const adminPasosWizardRoute = adminPasosWizardRouteImport.update({
  id: '/(admin)/pasos-wizard',
  path: '/pasos-wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const adminMenusRoute = adminMenusRouteImport.update({
  id: '/(admin)/menus',
  path: '/menus',
  getParentRoute: () => rootRouteImport,
} as any)
const adminMarcasRoute = adminMarcasRouteImport.update({
  id: '/(admin)/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const adminIndustriasRoute = adminIndustriasRouteImport.update({
  id: '/(admin)/industrias',
  path: '/industrias',
  getParentRoute: () => rootRouteImport,
} as any)
const adminFootersRoute = adminFootersRouteImport.update({
  id: '/(admin)/footers',
  path: '/footers',
  getParentRoute: () => rootRouteImport,
} as any)
const adminEmpresasRoute = adminEmpresasRouteImport.update({
  id: '/(admin)/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const adminDashboardRoute = adminDashboardRouteImport.update({
  id: '/(admin)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const adminContactosRoute = adminContactosRouteImport.update({
  id: '/(admin)/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const adminCategoriasRoute = adminCategoriasRouteImport.update({
  id: '/(admin)/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const adminAtributosRoute = adminAtributosRouteImport.update({
  id: '/(admin)/atributos',
  path: '/atributos',
  getParentRoute: () => rootRouteImport,
} as any)
const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/(admin)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atributos': typeof adminAtributosRoute
  '/categorias': typeof adminCategoriasRoute
  '/contactos': typeof adminContactosRoute
  '/dashboard': typeof adminDashboardRoute
  '/empresas': typeof adminEmpresasRoute
  '/footers': typeof adminFootersRoute
  '/industrias': typeof adminIndustriasRoute
  '/marcas': typeof adminMarcasRoute
  '/menus': typeof adminMenusRoute
  '/pasos-wizard': typeof adminPasosWizardRoute
  '/productos': typeof adminProductosRoute
  '/registros': typeof adminRegistrosRoute
  '/roles': typeof adminRolesRoute
  '/roles-auditoria': typeof adminRolesAuditoriaRoute
  '/secciones': typeof adminSeccionesRoute
  '/servicios': typeof adminServiciosRoute
  '/sucursales': typeof adminSucursalesRoute
  '/suscriptores': typeof adminSuscriptoresRoute
  '/tipos-atributo': typeof adminTiposAtributoRoute
  '/tipos-seccion': typeof adminTiposSeccionRoute
  '/usuarios': typeof adminUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atributos': typeof adminAtributosRoute
  '/categorias': typeof adminCategoriasRoute
  '/contactos': typeof adminContactosRoute
  '/dashboard': typeof adminDashboardRoute
  '/empresas': typeof adminEmpresasRoute
  '/footers': typeof adminFootersRoute
  '/industrias': typeof adminIndustriasRoute
  '/marcas': typeof adminMarcasRoute
  '/menus': typeof adminMenusRoute
  '/pasos-wizard': typeof adminPasosWizardRoute
  '/productos': typeof adminProductosRoute
  '/registros': typeof adminRegistrosRoute
  '/roles': typeof adminRolesRoute
  '/roles-auditoria': typeof adminRolesAuditoriaRoute
  '/secciones': typeof adminSeccionesRoute
  '/servicios': typeof adminServiciosRoute
  '/sucursales': typeof adminSucursalesRoute
  '/suscriptores': typeof adminSuscriptoresRoute
  '/tipos-atributo': typeof adminTiposAtributoRoute
  '/tipos-seccion': typeof adminTiposSeccionRoute
  '/usuarios': typeof adminUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/(admin)/_layout': typeof adminLayoutRoute
  '/(admin)/atributos': typeof adminAtributosRoute
  '/(admin)/categorias': typeof adminCategoriasRoute
  '/(admin)/contactos': typeof adminContactosRoute
  '/(admin)/dashboard': typeof adminDashboardRoute
  '/(admin)/empresas': typeof adminEmpresasRoute
  '/(admin)/footers': typeof adminFootersRoute
  '/(admin)/industrias': typeof adminIndustriasRoute
  '/(admin)/marcas': typeof adminMarcasRoute
  '/(admin)/menus': typeof adminMenusRoute
  '/(admin)/pasos-wizard': typeof adminPasosWizardRoute
  '/(admin)/productos': typeof adminProductosRoute
  '/(admin)/registros': typeof adminRegistrosRoute
  '/(admin)/roles': typeof adminRolesRoute
  '/(admin)/roles-auditoria': typeof adminRolesAuditoriaRoute
  '/(admin)/secciones': typeof adminSeccionesRoute
  '/(admin)/servicios': typeof adminServiciosRoute
  '/(admin)/sucursales': typeof adminSucursalesRoute
  '/(admin)/suscriptores': typeof adminSuscriptoresRoute
  '/(admin)/tipos-atributo': typeof adminTiposAtributoRoute
  '/(admin)/tipos-seccion': typeof adminTiposSeccionRoute
  '/(admin)/usuarios': typeof adminUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/atributos'
    | '/categorias'
    | '/contactos'
    | '/dashboard'
    | '/empresas'
    | '/footers'
    | '/industrias'
    | '/marcas'
    | '/menus'
    | '/pasos-wizard'
    | '/productos'
    | '/registros'
    | '/roles'
    | '/roles-auditoria'
    | '/secciones'
    | '/servicios'
    | '/sucursales'
    | '/suscriptores'
    | '/tipos-atributo'
    | '/tipos-seccion'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/atributos'
    | '/categorias'
    | '/contactos'
    | '/dashboard'
    | '/empresas'
    | '/footers'
    | '/industrias'
    | '/marcas'
    | '/menus'
    | '/pasos-wizard'
    | '/productos'
    | '/registros'
    | '/roles'
    | '/roles-auditoria'
    | '/secciones'
    | '/servicios'
    | '/sucursales'
    | '/suscriptores'
    | '/tipos-atributo'
    | '/tipos-seccion'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/(admin)/_layout'
    | '/(admin)/atributos'
    | '/(admin)/categorias'
    | '/(admin)/contactos'
    | '/(admin)/dashboard'
    | '/(admin)/empresas'
    | '/(admin)/footers'
    | '/(admin)/industrias'
    | '/(admin)/marcas'
    | '/(admin)/menus'
    | '/(admin)/pasos-wizard'
    | '/(admin)/productos'
    | '/(admin)/registros'
    | '/(admin)/roles'
    | '/(admin)/roles-auditoria'
    | '/(admin)/secciones'
    | '/(admin)/servicios'
    | '/(admin)/sucursales'
    | '/(admin)/suscriptores'
    | '/(admin)/tipos-atributo'
    | '/(admin)/tipos-seccion'
    | '/(admin)/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  adminLayoutRoute: typeof adminLayoutRoute
  adminAtributosRoute: typeof adminAtributosRoute
  adminCategoriasRoute: typeof adminCategoriasRoute
  adminContactosRoute: typeof adminContactosRoute
  adminDashboardRoute: typeof adminDashboardRoute
  adminEmpresasRoute: typeof adminEmpresasRoute
  adminFootersRoute: typeof adminFootersRoute
  adminIndustriasRoute: typeof adminIndustriasRoute
  adminMarcasRoute: typeof adminMarcasRoute
  adminMenusRoute: typeof adminMenusRoute
  adminPasosWizardRoute: typeof adminPasosWizardRoute
  adminProductosRoute: typeof adminProductosRoute
  adminRegistrosRoute: typeof adminRegistrosRoute
  adminRolesRoute: typeof adminRolesRoute
  adminRolesAuditoriaRoute: typeof adminRolesAuditoriaRoute
  adminSeccionesRoute: typeof adminSeccionesRoute
  adminServiciosRoute: typeof adminServiciosRoute
  adminSucursalesRoute: typeof adminSucursalesRoute
  adminSuscriptoresRoute: typeof adminSuscriptoresRoute
  adminTiposAtributoRoute: typeof adminTiposAtributoRoute
  adminTiposSeccionRoute: typeof adminTiposSeccionRoute
  adminUsuariosRoute: typeof adminUsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/usuarios': {
      id: '/(admin)/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof adminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/tipos-seccion': {
      id: '/(admin)/tipos-seccion'
      path: '/tipos-seccion'
      fullPath: '/tipos-seccion'
      preLoaderRoute: typeof adminTiposSeccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/tipos-atributo': {
      id: '/(admin)/tipos-atributo'
      path: '/tipos-atributo'
      fullPath: '/tipos-atributo'
      preLoaderRoute: typeof adminTiposAtributoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/suscriptores': {
      id: '/(admin)/suscriptores'
      path: '/suscriptores'
      fullPath: '/suscriptores'
      preLoaderRoute: typeof adminSuscriptoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/sucursales': {
      id: '/(admin)/sucursales'
      path: '/sucursales'
      fullPath: '/sucursales'
      preLoaderRoute: typeof adminSucursalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/servicios': {
      id: '/(admin)/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof adminServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/secciones': {
      id: '/(admin)/secciones'
      path: '/secciones'
      fullPath: '/secciones'
      preLoaderRoute: typeof adminSeccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/roles-auditoria': {
      id: '/(admin)/roles-auditoria'
      path: '/roles-auditoria'
      fullPath: '/roles-auditoria'
      preLoaderRoute: typeof adminRolesAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/roles': {
      id: '/(admin)/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof adminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/registros': {
      id: '/(admin)/registros'
      path: '/registros'
      fullPath: '/registros'
      preLoaderRoute: typeof adminRegistrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/productos': {
      id: '/(admin)/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof adminProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/pasos-wizard': {
      id: '/(admin)/pasos-wizard'
      path: '/pasos-wizard'
      fullPath: '/pasos-wizard'
      preLoaderRoute: typeof adminPasosWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/menus': {
      id: '/(admin)/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof adminMenusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/marcas': {
      id: '/(admin)/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof adminMarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/industrias': {
      id: '/(admin)/industrias'
      path: '/industrias'
      fullPath: '/industrias'
      preLoaderRoute: typeof adminIndustriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/footers': {
      id: '/(admin)/footers'
      path: '/footers'
      fullPath: '/footers'
      preLoaderRoute: typeof adminFootersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/empresas': {
      id: '/(admin)/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof adminEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/dashboard': {
      id: '/(admin)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof adminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/contactos': {
      id: '/(admin)/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof adminContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/categorias': {
      id: '/(admin)/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof adminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/atributos': {
      id: '/(admin)/atributos'
      path: '/atributos'
      fullPath: '/atributos'
      preLoaderRoute: typeof adminAtributosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/_layout': {
      id: '/(admin)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  adminLayoutRoute: adminLayoutRoute,
  adminAtributosRoute: adminAtributosRoute,
  adminCategoriasRoute: adminCategoriasRoute,
  adminContactosRoute: adminContactosRoute,
  adminDashboardRoute: adminDashboardRoute,
  adminEmpresasRoute: adminEmpresasRoute,
  adminFootersRoute: adminFootersRoute,
  adminIndustriasRoute: adminIndustriasRoute,
  adminMarcasRoute: adminMarcasRoute,
  adminMenusRoute: adminMenusRoute,
  adminPasosWizardRoute: adminPasosWizardRoute,
  adminProductosRoute: adminProductosRoute,
  adminRegistrosRoute: adminRegistrosRoute,
  adminRolesRoute: adminRolesRoute,
  adminRolesAuditoriaRoute: adminRolesAuditoriaRoute,
  adminSeccionesRoute: adminSeccionesRoute,
  adminServiciosRoute: adminServiciosRoute,
  adminSucursalesRoute: adminSucursalesRoute,
  adminSuscriptoresRoute: adminSuscriptoresRoute,
  adminTiposAtributoRoute: adminTiposAtributoRoute,
  adminTiposSeccionRoute: adminTiposSeccionRoute,
  adminUsuariosRoute: adminUsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
